<?  include_once ('conectar.php');


class layout_email{

    function layout_agendamento($razaosocial,$email_contato,$Nome,$nomecontato,$email,$operador_pk,$codlead,$codagendalead,$dt_agenda,$hr_agenda,$site,$ddd,$tel,$ddd,$enderecoo,$numero,$bairro,$cidade,$cep,$razaosocial_empresa){
            
    $endereco = $_SERVER['SERVER_NAME'];    
        
            if($operador_pk==3){
                //vivo
                $html .="          <p align='center'><img src=http://'$endereco/images/email/vivo_agenda.png'></p>";                
            }else if($operador_pk==2){
                //tim
                $html .="          <p align='center'><img src=http://'$endereco/images/email/tim_agenda.png'></p>"; 
                //claro
            }else if ($operador_pk==1){
               $html .="          <p align='center'><img src=http://'$endereco/images/email/claro_agenda.png'></p>"; 
            }else if ($operador_pk==4){
               $html .="          <p align='center'><img src=http://'$endereco/images/email/nextel_agenda.png'></p>";   
            }else if ($operador_pk==6){
               $html .="          <p align='center'><img src=http://'$endereco/images/email/oi_agenda.png'></p>";      
            }               
                $html .="          <div align='center'>";
                $html .="            <table border='0' cellpadding='0' cellspacing='0' width='680'>";
                $html .="              <tbody>";
                $html .="                <tr>";
                $html .="                  <td><div align='center'>";
                $html .="                    <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html .="                      <tbody>";
                $html .="                        <tr>";
                $html .="                         <td><p>Prezado cliente,</p>";
                $html .="                            <p>".$nomecontato."</p>";
                $html .="                            <p>".$razaosocial."</p>";
                $html .="                            <p>Conforme contato com nossa central de relacionamento, segue abaixo a confirmação de nossa visita comercial.</p></td>";
                $html .="                        </tr>";
                $html .="                      </tbody>";
                $html .="                    </table>";
                $html .="                  </div></td>";
                $html .="                </tr>";
                $html .="              </tbody>";
                $html .="            </table>";
                $html .="          </div>";
                $html .="          <p align='center'> </p>";
                $html .="          <div align='center'>";
                $html .="            <table border='0' cellpadding='0' cellspacing='0' width='680'>";
                $html .="              <tbody>";
                $html .="                <tr>";
                $html .="                  <td>";
                $html .="                    <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html .="                      <tbody>";
                $html .="                        <tr>";
                $html .="                          <td><p align='center'><strong>PROTOCOLO</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>ASSUNTO</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>DATA DA VISITA</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>HORÁRIO</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>CONSULTOR</strong><strong> </strong></p></td>";
                $html .="                        </tr>";
                $html .="                        <tr>";
                $html .="                          <td><p align='center'> ".$codlead."</p></td>";
                $html .="                          <td><p align='center'> PORTABILIDADE</p></td>";
                $html .="                          <td><p align='center'> ".$dt_agenda."</p></td>";
                $html .="                          <td><p align='center'> ".$hr_agenda."</p></td>";
                $html .="                          <td><p align='center'> ".$Nome."</p></td>";
                $html .="                        </tr>";
                $html .="                        <tr>";
                $html .="                          <td></td>";
                $html .="                          <td><p align='center'> - </p></td>";
                $html .="                          <td><p align='center'> - </p></td>";
                $html .="                          <td><p align='center'> - </p></td>";
                $html .="                          <td><p align='center'> - </p></td>";
                $html .="                        </tr>";
                $html .="                        <tr>";
                $html .="                         <td><p align='center'><strong>Endereço da visita</strong><strong> </strong></p></td>";
                $html .="                          <td>".$enderecoo.", ".$numero."<br>Bairro: ".$bairro."<br>Cidade: ".$cidade."/ ".$cep."</td><br>";
                $html .="                          <td></td>";
                $html .="                          <td></td>";
                $html .="                          <td></td>";
                $html .="                        </tr>";
                $html .="                      </tbody>";
                $html .="                    </table>";
                $html .="                  </td>";
                $html .="                <tr>";
                $html .="                   <td>";
                $html .="                       &nbsp;";
                $html .="                   </td>";
                $html .="                </tr>";
                $html .="                <tr>";
                $html .="                   <td>";
                $html .="                     <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html.="                          <tr>";
                $html.="                              <td>";
                $html.="                                  - Em caso do cliente já possuir planos corporativos o mesmo deve separar a última fatura  completa para que o consultor possa analisar na hora da visita o perfil de uso adequado para a sua empresa";
                $html.="                              </td>";
                $html.="                          </tr>";
                $html.="                          <tr>";
                $html.="                              <td>";
                $html.="                                 <b> A empresa visitada fica ciente que não possuímos atendimento para as seguintes situações</b>";
                $html.="                              </td>";
                $html.="                          </tr>";
                $html.="                          <tr>";
                $html.="                              <td>";
                $html.="                               - Atendimento pessoa Física;<br>";
                $html.="                               - Telefonia Fixa;<br>";
                $html.="                               - Órgãos Governamentais;<br>";
                $html.="                               - Empresas com restrições no CPF dos sócios ou no CNPJ;<br>";
                $html.="                               - Empresas no regime MEI com menos de 5 meses.";
                $html.="                              </td>";                
                $html.="                          </tr>";                
                $html.="                       </table>";                
                $html.="                    </td>";                
                $html.="                 </tr>";                
                $html .="              </tbody>";
                $html .="            </table>";
                $html .="          </div>";
                $html .="          <div align='center'>";
                $html .="            <table border='0' cellpadding='0' cellspacing='0' width='680'>";
                $html .="              <tbody>";
                $html .="                 <tr>";
                $html .="                  <td>";
                $html.= "                       <div align='center'>";
                $html .="                           <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html .="                               <tbody>";
                $html .="                                   <tr>";
                $html .="                                       <td><p><strong>Observação:</strong> se necessário, a(s) data(s) e o(s) turno(s) acima poderão ser reagendados entre as partes através de um novo contato.</p></td>";
                $html .="                                   </tr>";
                $html .="                               </tbody>";
                $html .="                           </table>";
                $html .="                       </div>";
                $html .="                  </td>";
                $html .="                </tr>";
                $html .="              </tbody>";
                $html .="            </table>";
                $html .="          </div>";
                $html.="                  <tr>";
                $html.="                    <td>";
                $html.="                        <table width='100%' align='center'>";
                $html.="                            <tr align='center'>";
                $html.="                                <td>";
                $html .="                                   <strong>$site</strong><br>";    
                $html .="                                   (".$ddd.")".$tel."<br>";    
                $html .="                                   $razaosocial_empresa<br>";
                $html.="                                </td>";                
                $html.="                            </tr>";                
                $html.="                        </table>";                
                $html.="                    </td>";                
                $html.="                </tr>"; 
                $html .="<div align='center'>";
                $html .="  <table border='0' cellpadding='0' cellspacing='0'>";
                $html .="    <tbody>";
                $html .="      <tr>";
                $html .="        <td><p align='center'> </p></td>";
                $html .="        <td><p align='center'> </p></td>";
                $html .="      </tr>";
                $html .="    </tbody>";
                $html .="  </table>";
                $html .="</div>";
                $html .="<p> </p>";
                $html .="</body>";
                $html .="</html>"; 

         return($html);
    }
        function layout_bko($leads_pk,$operador_pk,$assunto,$vl_data,$vl_obs_data,$n_pedido,$vl_pedido,$Consultor,$razaosocial,$cnpj_cpf,$nomeusuario){
                $html .="          <div align='center'>";
                $html .="            <table border='0' cellpadding='0' cellspacing='0' width='680'>";
                $html .="              <tbody>";
                $html .="                <tr>";
                $html .="                  <td><div align='center'>";
                $html .="                    <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html .="                      <tbody>";
                $html .="                        <tr>";
                $html .="                         <td><p>Prezado consultor</p>";
                $html .="                            <p>".$Consultor."</p>";
                $html .="                            <p>Seu pedido foi atualizado, conforme as informações abaixo.</p></td>";
                $html .="                        </tr>";
                $html .="                      </tbody>";
                $html .="                    </table>";
                $html .="                  </div></td>";
                $html .="                </tr>";
                $html .="              </tbody>";
                $html .="            </table>";
                $html .="          </div>";
                $html .="          <p align='center'> </p>";
                $html .="          <div align='center'>";
                $html .="            <table border='0' cellpadding='0' cellspacing='0' width='680'>";
                $html .="              <tbody>";
                $html .="                <tr>";
                $html .="                  <td>";
                $html .="                    <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html .="                      <tbody>";
                $html .="                        <tr>";
                $html .="                          <td><p align='center'><strong>PROTOCOLO</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>ASSUNTO</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>DATA </strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>BKO </strong><strong> </strong></p></td>";
                $html .="                        </tr>";
                $html .="                        <tr>";
                $html .="                          <td><p align='center'>".$leads_pk."</p></td>";
                $html .="                          <td><p align='center'>$assunto</p></td>";
                $html .="                          <td><p align='center'>".$vl_data."</p></td>";
                $html .="                          <td><p align='center'>".$nomeusuario."</p></td>";
                $html .="                        </tr>";                
                $html.="                       </table>";                
                $html.="                    </td>";                
                $html.="                 </tr>";
                $html .="                <tr>";
                $html .="                   <td>";
                $html .="                       &nbsp;";
                $html .="                    </td>";
                $html .="                 </tr>";
                $html .="              </tbody>";
                $html .="            </table>";
                $html .="          </div>";
                $html.="            <div align='center'>";
                $html .="            <table border='0' cellpadding='0' cellspacing='0' width='680'>";
                $html .="              <tbody>";
                $html .="                <tr>";
                $html .="                  <td>";
                $html .="                    <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html .="                      <tbody>";
                $html .="                        <tr>";
                $html.="                               <td align='center'>";   
                $html .="                                  <b>Descrição</b>";
                $html.="                                </td>";
                $html.="                          </tr>";
                $html.="                          <tr>";
                $html.="                               <td align='center'>";   
                $html.=                                  $vl_obs_data;
                $html.="                               </td>";                               
                $html .="                        </tr>";                
                $html.="                       </table>";                
                $html.="                    </td>";                
                $html.="                 </tr>";
                $html .="                <tr>";
                $html .="                   <td>";
                $html .="                       &ensp;";
                $html .="                    </td>";
                $html .="                 </tr>";
                $html .="                <tr>";
                $html .="                   <td>";
                $html .="                       &ensp;";
                $html .="                    </td>";
                $html .="                 </tr>";
                $html .="              </tbody>";
                $html .="            </table>";
                $html.="            <div align='center'>";
                $html .="            <table border='0' cellpadding='0' cellspacing='0' width='680'>";
                $html .="              <tbody>";
                $html .="                <tr>";
                $html .="                  <td>";
                $html .="                    <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html .="                      <tbody>";
                $html .="                        <tr>";
                $html.="                               <td align='left'>";   
                $html .="                                  Razão social: <b>".$razaosocial;
                $html.="                                </td>";
                $html.="                          </tr>";
                $html.="                          <tr>";
                $html.="                            <td>";
                $html.="                                &nbsp;";
                $html.="                            </td>";
                $html.="                          </tr>";
                $html.="                          <tr>";
                $html.="                               <td align='left'>";   
                $html .="                                  CNPJ: <b>".$cnpj_cpf;
                $html.="                                </td>";                               
                $html .="                        </tr>";                
                $html.="                       </table>";                
                $html.="                    </td>";                
                $html.="                 </tr>";                
                $html .="              </tbody>";
                $html .="            </table>";
                $html .="          </div>";
                $html .="<div align='center'>";
                $html .="  <table border='0' cellpadding='0' cellspacing='0'>";
                $html .="    <tbody>";
                $html .="      <tr>";
                $html .="        <td><p align='center'> </p></td>";
                $html .="        <td><p align='center'> </p></td>";
                $html .="      </tr>";
                $html .="    </tbody>";
                $html .="  </table>";
                $html .="</div>";
                $html .="<p> </p>";
                $html .="</body>";
                $html .="</html>"; 
                
         return($html);
    }
    function layout_solicitacao($nome,$dsc_operadora,$codlead,$razaosocial,$ddd,$tel,$NomeContato,$email_contato,$DDD_fone,$fone) {
                $html .="          <div align='center'>";
                $html .="            <table border='0' cellpadding='0' cellspacing='0' width='680'>";
                $html .="              <tbody>";
                $html .="                <tr>";
                $html .="                  <td><div align='center'>";
                $html .="                    <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html .="                      <tbody>";
                $html .="                        <tr>";
                $html .="                         <td><p>Prezado consultor,</p>";
                $html .="                            <p>".$nome."</p>";
                $html .="                            <p>Solicitação de proposta para operadora $dsc_operadora, seguem os dados a baixo do solicitante.</p></td>";
                $html .="                        </tr>";
                $html .="                      </tbody>";
                $html .="                    </table>";
                $html .="                  </div></td>";
                $html .="                </tr>";
                $html .="              </tbody>";
                $html .="            </table>";
                $html .="          </div>";
                $html .="          <p align='center'> </p>";
                $html .="          <div align='center'>";
                $html .="            <table border='0' cellpadding='0' cellspacing='0' width='680'>";
                $html .="              <tbody>";
                $html .="                <tr>";
                $html .="                  <td>";
                $html .="                    <table border='0' cellpadding='0' cellspacing='0' width='100%'>";
                $html .="                      <tbody>";
                $html .="                        <tr>";
                $html .="                          <td><p align='center'><strong>Código do lead</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>Razão Social</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>Telefone</strong><strong> </strong></p></td>";
                $html .="                        </tr>";
                $html .="                        <tr>";
                $html .="                          <td><p align='center'> ".$codlead."</p></td>";
                $html .="                          <td><p align='center'> ".$razaosocial."</p></td>";
                $html .="                          <td><p align='center'> (".$ddd.")".$tel."</p></td>";
                $html .="                        </tr>";
                $html .="                        <tr>";
                $html .="                          <td><p align='center'><strong>Nome do contato</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>Email do contato</strong><strong> </strong></p></td>";
                $html .="                          <td><p align='center'><strong>Telefone do contato</strong><strong> </strong></p></td>";
                $html .="                          <td></td>";
                $html.="                        </tr>";
                $html.="                        <tr>";
                $html .="                          <td><p align='center'> ".$NomeContato."</p></td>";
                $html .="                          <td><p align='center'> ".$email_contato."</p></td>";
                $html .="                          <td><p align='center'> (".$DDD_fone.")".$fone."</p></td>";
                $html .="                        </tr>";
                $html .="                      </tbody>";
                $html .="                    </table>";
                $html .="                  </td>";
                $html .="                <tr>";
                $html .="                   <td>";
                $html .="                       &nbsp;";
                $html .="                   </td>";
                $html .="                </tr>";              
                $html .="              </tbody>";
                $html .="            </table>";
                $html .="          </div>";
                $html .="<div align='center'>";
                $html .="  <table border='0' cellpadding='0' cellspacing='0'>";
                $html .="    <tbody>";
                $html .="      <tr>";
                $html .="        <td><p align='center'> </p></td>";
                $html .="        <td><p align='center'> </p></td>";
                $html .="      </tr>";
                $html .="    </tbody>";
                $html .="  </table>";
                $html .="</div>";
                $html .="<p> </p>";
                $html .="</body>";
                $html .="</html>"; 
                
                return($html);
    }
                
}
    

