<?
echo '{';
echo '"sEmptyTable": "Nenhum registro encontrado",';
echo '    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",';
echo '    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",';
echo '    "sInfoFiltered": "(Filtrados de _MAX_ registros",';
echo '    "sInfoPostFix": "",';
echo '    "sInfoThousands": ".",';
echo '    "sLengthMenu": "_MENU_ resultados por página",';
echo '    "sLoadingRecords": "Carregando...",';
echo '    "sProcessing": "Processando...",';
echo '    "sZeroRecords": "Nenhum registro encontrado",';
echo '    "sSearch": "Pesquisar",';
echo '    "oPaginate": {';
echo '        "sNext": "Próximo",';
echo '        "sPrevious": "Anterior",';
echo '        "sFirst": "Primeiro",';
echo '        "sLast": "Último"';
echo '    },';
echo '    "oAria": {';
echo '        "sSortAscending": ": Ordenar colunas de forma ascendente",';
echo '        "sSortDescending": ": Ordenar colunas de forma descendente"';
echo '    },';
echo '    "select": {';
echo '        "rows": {';
echo '            "_": "Selecionado %d linhas",';
echo '            "0": "Nenhuma linha selecionada",';
echo '            "1": "Selecionado 1 linha"';
echo '        }';
echo '    }';
echo '}';
?>
