ServerName ${APACHE_SERVER_NAME}

<VirtualHost *:80>
    ServerName ${APACHE_SERVER_NAME}
    DocumentRoot ${APACHE_DOCUMENT_ROOT}

    <Directory ${APACHE_DOCUMENT_ROOT}>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html
    </Directory>

    Alias /docs ${APACHE_DOCS_ROOT}
    <Directory ${APACHE_DOCS_ROOT}>
        Options FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
